# Generated by Django 3.2.14 on 2022-07-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('type', models.CharField(max_length=255)),
                ('handlebar', models.CharField(max_length=255)),
                ('marches', models.IntegerField(default=0)),
                ('material', models.CharField(max_length=255)),
                ('cube', models.CharField(max_length=255)),
                ('rear_cube', models.CharField(max_length=255)),
                ('tires', models.CharField(max_length=255)),
            ],
        ),
    ]
