# Generated by Django 3.2.14 on 2022-07-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_bicycle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
